using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.CodeAnalysis.CSharp;

namespace Structura.Generator;

/// <summary>
/// Generates the C# source for a JSON-backed document model from
/// <see cref="JsonRootInfo"/>. Supports root + nested objects, primitive and
/// object array collections, and heterogeneous field unions inside array items
/// (with <c>StructuraMutationException</c> setters for absent source spans).
/// Empty / heterogeneous collections are silently dropped here — the caller
/// (<see cref="StructuraJsonGenerator"/>) is responsible for surfacing the
/// matching diagnostics.
/// </summary>
internal static class JsonModelEmitter
{
    public static string Emit(string className, string sourceFileName, JsonRootInfo info)
    {
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Structura.Runtime;");
        sb.AppendLine("using Structura.Runtime.Json;");
        sb.AppendLine();
        sb.AppendLine("namespace Structura.Generated;");
        sb.AppendLine();

        sb.Append("public sealed partial class ").Append(className);
        sb.AppendLine();
        sb.Append("    : IStructuraJsonDocument<").Append(className).AppendLine(">, IStructuraDocument");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly StructuraDocumentContext _ctx;");
        sb.AppendLine();

        // ── Static SourceFileName (interface contract) ────────────────────────
        string sourceFileNameLiteral = SymbolDisplay.FormatLiteral(sourceFileName, quote: true);
        sb.Append("    public static string SourceFileName => ")
          .Append(sourceFileNameLiteral)
          .AppendLine(";");
        sb.AppendLine();

        EmitObjectMembers(
            sb,
            obj: info.Root,
            className: className,
            isRoot: true,
            classIndent: "    ",
            ctorIndent: "        ",
            sourceObjectVar: "root");

        // ── ParseFromJson factory ────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    public static ").Append(className).AppendLine(" ParseFromJson(string source)");
        sb.AppendLine("    {");
        sb.AppendLine("        var rootNode = JsonSourceParser.Parse(source);");
        sb.AppendLine("        if (rootNode is not JsonSourceObject obj)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new JsonParseException(\"Expected JSON object at root.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        return new ").Append(className).AppendLine("(source, obj);");
        sb.AppendLine("    }");

        // ── ToJson + IStructuraDocument plumbing ─────────────────────────────
        sb.AppendLine();
        sb.AppendLine("    public string ToJson() => _ctx.ApplyEdits();");
        sb.AppendLine();
        sb.AppendLine("    string IStructuraDocument.OriginalText  => _ctx.OriginalText;");
        sb.AppendLine("    string IStructuraDocument.CurrentText   => _ctx.ApplyEdits();");
        sb.AppendLine("    string IStructuraDocument.DocumentName  => _ctx.DocumentName;");
        sb.AppendLine("    IReadOnlyList<DocumentChange> IStructuraDocument.Changes => _ctx.Changes;");

        // ── Nested types (depth-first) ───────────────────────────────────────
        // Nested types are emitted as members of their parent class, not as
        // flat siblings of the root, so the same JSON key name appearing under
        // different parents (e.g. `price.price_with_vat` and
        // `price.price_spt.price_with_vat`) yields distinct C# types in
        // separate scopes (`PriceType.PriceWithVatType` vs
        // `PriceSptType.PriceWithVatType`) instead of colliding on CS0102.
        EmitNestedTypesRecursive(sb, info.Root, classIndent: "    ");

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Member emission for an object body (root or nested) ──────────────────

    /// <summary>
    /// Emits all the fields, the constructor, and the public properties for
    /// the body of <paramref name="obj"/>. The opening <c>class { ... }</c> and
    /// the trailing <c>}</c> are the caller's responsibility.
    /// </summary>
    private static void EmitObjectMembers(
        StringBuilder sb,
        JsonGenObject obj,
        string className,
        bool isRoot,
        string classIndent,
        string ctorIndent,
        string sourceObjectVar)
    {
        ObjectBindings bindings = ResolveBindings(obj);
        EmitBackingFields(sb, bindings, classIndent, isRoot);
        EmitConstructor(sb, bindings, className, isRoot, classIndent, ctorIndent, sourceObjectVar);
        EmitPublicProperties(sb, bindings, classIndent, ctorIndent, isRoot);
    }

    /// <summary>
    /// Carries the resolved-name C# bindings for one object scope: the three
    /// lists are produced by <see cref="ResolveBindings"/> and consumed by the
    /// three subsequent emission phases.
    /// </summary>
    private sealed class ObjectBindings
    {
        public ObjectBindings(
            List<ScalarBinding> scalars,
            List<NestedObjectBinding> nestedObjects,
            List<CollectionBinding> collections)
        {
            Scalars = scalars;
            NestedObjects = nestedObjects;
            Collections = collections;
        }

        public List<ScalarBinding> Scalars { get; }
        public List<NestedObjectBinding> NestedObjects { get; }
        public List<CollectionBinding> Collections { get; }
    }

    private static ObjectBindings ResolveBindings(JsonGenObject obj)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        var scalars = new List<ScalarBinding>();
        foreach (JsonGenProperty prop in obj.Scalars)
        {
            scalars.Add(BuildScalarBinding(prop, obj.RequiredKeys.Contains(prop.Name), usedNames));
        }

        var nestedBindings = new List<NestedObjectBinding>();
        foreach (JsonGenNestedObject n in obj.NestedObjects)
        {
            string pascalKey = IdentifierSanitizer.ToPascalCase(n.Name);
            string propName = MakeUnique(pascalKey, usedNames);
            // Class name must differ from the property name (CS0102: a property
            // and a nested class on the same outer can't share a name). XML uses
            // a "Group" suffix for the same situation; JSON uses "Type".
            string typeName = NestedObjectTypeName(n.Name);
            nestedBindings.Add(new NestedObjectBinding(
                jsonKey: n.Name,
                propertyName: propName,
                fieldName: ToCamel(propName),
                typeName: typeName));
        }

        var collectionBindings = new List<CollectionBinding>();
        foreach (JsonGenCollection coll in obj.Collections)
        {
            // Empty / heterogeneous → emitter silently drops; diagnostics
            // are reported separately by the generator.
            if (coll.ItemKind == JsonGenItemKind.Empty || coll.ItemKind == JsonGenItemKind.Heterogeneous)
            {
                continue;
            }

            string pascalKey = IdentifierSanitizer.ToPascalCase(coll.Name);
            string propName = MakeUnique(pascalKey, usedNames);
            string itemTypeName;
            if (coll.ItemKind == JsonGenItemKind.Primitive)
            {
                itemTypeName = CSharpTypeFor(coll.PrimitiveItemKind!.Value);
            }
            else
            {
                itemTypeName = SingularizeForItemType(coll.Name, propName);
            }
            collectionBindings.Add(new CollectionBinding(
                jsonKey: coll.Name,
                propertyName: propName,
                fieldName: ToCamel(propName),
                itemTypeName: itemTypeName,
                collection: coll));
        }

        return new ObjectBindings(scalars, nestedBindings, collectionBindings);
    }

    private static void EmitBackingFields(
        StringBuilder sb,
        ObjectBindings bindings,
        string classIndent,
        bool isRoot)
    {
        if (!isRoot)
        {
            // Each nested class carries its own _ctx reference so the
            // record-edit calls compile inside its setter bodies.
            sb.Append(classIndent).AppendLine("private readonly StructuraDocumentContext _ctx;");
            sb.Append(classIndent).AppendLine("private readonly string _pathPrefix;");
        }

        foreach (ScalarBinding s in bindings.Scalars)
        {
            sb.AppendLine();
            if (!s.IsRequired)
            {
                sb.Append(classIndent).Append("private readonly bool _").Append(s.FieldName).AppendLine("IsPresent;");
            }
            sb.Append(classIndent).Append("private readonly TextSpan _").Append(s.FieldName).AppendLine("ValueSpan;");
            sb.Append(classIndent).Append("private ").Append(s.CSharpType).Append(" _").Append(s.FieldName).AppendLine(";");
        }

        foreach (NestedObjectBinding n in bindings.NestedObjects)
        {
            sb.AppendLine();
            sb.Append(classIndent).Append("private readonly ").Append(n.TypeName).Append(" _").Append(n.FieldName).AppendLine(";");
        }

        foreach (CollectionBinding c in bindings.Collections)
        {
            sb.AppendLine();
            sb.Append(classIndent).Append("private readonly IReadOnlyList<").Append(c.ItemTypeName).Append("> _").Append(c.FieldName).AppendLine(";");
        }
    }

    private static void EmitConstructor(
        StringBuilder sb,
        ObjectBindings bindings,
        string className,
        bool isRoot,
        string classIndent,
        string ctorIndent,
        string sourceObjectVar)
    {
        sb.AppendLine();
        if (isRoot)
        {
            sb.Append(classIndent).Append("private ").Append(className).AppendLine("(string source, JsonSourceObject root)");
            sb.Append(classIndent).AppendLine("{");
            sb.Append(ctorIndent).AppendLine("_ctx = new StructuraDocumentContext(source, SourceFileName);");
        }
        else
        {
            sb.Append(classIndent).Append("internal ").Append(className).AppendLine("(StructuraDocumentContext ctx, string pathPrefix, JsonSourceObject obj)");
            sb.Append(classIndent).AppendLine("{");
            sb.Append(ctorIndent).AppendLine("_ctx = ctx;");
            sb.Append(ctorIndent).AppendLine("_pathPrefix = pathPrefix;");
        }

        foreach (ScalarBinding s in bindings.Scalars)
        {
            EmitScalarCtorAssignment(sb, s, sourceObjectVar, ctorIndent);
        }

        foreach (NestedObjectBinding n in bindings.NestedObjects)
        {
            EmitNestedCtorAssignment(sb, n, sourceObjectVar, isRoot, ctorIndent);
        }

        foreach (CollectionBinding c in bindings.Collections)
        {
            EmitCollectionCtorAssignment(sb, c, sourceObjectVar, isRoot, ctorIndent);
        }

        sb.Append(classIndent).AppendLine("}");
    }

    private static void EmitPublicProperties(
        StringBuilder sb,
        ObjectBindings bindings,
        string classIndent,
        string ctorIndent,
        bool isRoot)
    {
        foreach (ScalarBinding s in bindings.Scalars)
        {
            EmitScalarProperty(sb, s, isRoot, classIndent, ctorIndent);
        }

        foreach (NestedObjectBinding n in bindings.NestedObjects)
        {
            sb.AppendLine();
            sb.Append(classIndent).Append("public ").Append(n.TypeName).Append(' ').Append(n.PropertyName)
              .Append(" => _").Append(n.FieldName).AppendLine(";");
        }

        foreach (CollectionBinding c in bindings.Collections)
        {
            sb.AppendLine();
            sb.Append(classIndent).Append("public IReadOnlyList<").Append(c.ItemTypeName).Append("> ")
              .Append(c.PropertyName).Append(" => _").Append(c.FieldName).AppendLine(";");
        }
    }

    // ── Scalar bindings ──────────────────────────────────────────────────────

    private sealed class ScalarBinding
    {
        public ScalarBinding(
            string jsonKey,
            string propertyName,
            string fieldName,
            string cSharpType,
            JsonGenScalarKind kind,
            bool isRequired)
        {
            JsonKey = jsonKey;
            PropertyName = propertyName;
            FieldName = fieldName;
            CSharpType = cSharpType;
            Kind = kind;
            IsRequired = isRequired;
            JsonPointerSegment = JsonPointerEscaper.Escape(jsonKey);
        }

        public string JsonKey { get; }
        public string PropertyName { get; }
        public string FieldName { get; }
        public string CSharpType { get; }
        public JsonGenScalarKind Kind { get; }
        public bool IsRequired { get; }
        public string JsonPointerSegment { get; } // includes leading '/'
    }

    private static ScalarBinding BuildScalarBinding(JsonGenProperty prop, bool isRequired, HashSet<string> usedNames)
    {
        string propertyName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        return new ScalarBinding(
            jsonKey: prop.Name,
            propertyName: propertyName,
            fieldName: ToCamel(propertyName),
            cSharpType: CSharpTypeFor(prop.Kind),
            kind: prop.Kind,
            isRequired: isRequired);
    }

    private static void EmitScalarCtorAssignment(StringBuilder sb, ScalarBinding s, string sourceObjectVar, string indent)
    {
        string lookupVar = s.FieldName + "Prop";

        if (s.IsRequired)
        {
            sb.AppendLine();
            sb.Append(indent).Append("var ").Append(lookupVar).Append(" = ").Append(sourceObjectVar)
              .Append(".RequireProperty(\"").Append(EscapeForCsString(s.JsonKey)).AppendLine("\");");
            sb.Append(indent).Append("_").Append(s.FieldName).Append("ValueSpan = ").Append(lookupVar).AppendLine(".ValueSpan;");
            sb.Append(indent).Append("_").Append(s.FieldName).Append(" = ")
              .Append(ScalarReadExpr(s.Kind, lookupVar + ".Value")).AppendLine(";");
        }
        else
        {
            sb.AppendLine();
            sb.Append(indent).Append("var ").Append(lookupVar).Append(" = ").Append(sourceObjectVar)
              .Append(".FindProperty(\"").Append(EscapeForCsString(s.JsonKey)).AppendLine("\");");
            sb.Append(indent).Append("_").Append(s.FieldName).Append("IsPresent = ").Append(lookupVar).AppendLine(" is not null;");
            sb.Append(indent).Append("_").Append(s.FieldName).Append("ValueSpan = ").Append(lookupVar).AppendLine("?.ValueSpan ?? default;");
            sb.Append(indent).Append("_").Append(s.FieldName).Append(" = ").Append(lookupVar).Append(" is null ? ")
              .Append(DefaultValueExpr(s.Kind)).Append(" : ").Append(ScalarReadExpr(s.Kind, lookupVar + ".Value")).AppendLine(";");
        }
    }

    private static void EmitScalarProperty(StringBuilder sb, ScalarBinding s, bool isRoot, string classIndent, string bodyIndent)
    {
        sb.AppendLine();
        sb.Append(classIndent).Append("public ").Append(s.CSharpType).Append(' ').AppendLine(s.PropertyName);
        sb.Append(classIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("get => _").Append(s.FieldName).AppendLine(";");
        sb.Append(bodyIndent).AppendLine("set");
        sb.Append(bodyIndent).AppendLine("{");

        string innerIndent = bodyIndent + "    ";

        if (!s.IsRequired)
        {
            sb.Append(innerIndent).Append("if (!_").Append(s.FieldName).AppendLine("IsPresent)");
            sb.Append(innerIndent).AppendLine("{");
            sb.Append(innerIndent).Append("    throw new StructuraMutationException(\"Cannot update field '")
              .Append(EscapeForCsString(s.PropertyName))
              .Append("' on this object because the source key '")
              .Append(EscapeForCsString(s.JsonKey))
              .Append("' is absent. Insertion is not supported in V1; this field exists in the model only because some sibling object provided it.\");");
            sb.AppendLine();
            sb.Append(innerIndent).AppendLine("}");
        }

        sb.Append(innerIndent).Append("_").Append(s.FieldName).AppendLine(" = value;");

        string pathExpr = isRoot
            ? ("\"" + s.JsonPointerSegment + "\"")
            : ("_pathPrefix + \"" + s.JsonPointerSegment + "\"");

        sb.Append(innerIndent).Append("_ctx.Record(").Append(pathExpr).Append(", _")
          .Append(s.FieldName).Append("ValueSpan, ").Append(WriterCallFor(s.Kind)).AppendLine(");");

        sb.Append(bodyIndent).AppendLine("}");
        sb.Append(classIndent).AppendLine("}");
    }

    // ── Nested object bindings ───────────────────────────────────────────────

    private sealed class NestedObjectBinding
    {
        public NestedObjectBinding(string jsonKey, string propertyName, string fieldName, string typeName)
        {
            JsonKey = jsonKey;
            PropertyName = propertyName;
            FieldName = fieldName;
            TypeName = typeName;
            JsonPointerSegment = JsonPointerEscaper.Escape(jsonKey);
        }

        public string JsonKey { get; }
        public string PropertyName { get; }
        public string FieldName { get; }
        public string TypeName { get; }
        public string JsonPointerSegment { get; }
    }

    private static void EmitNestedCtorAssignment(StringBuilder sb, NestedObjectBinding n, string sourceObjectVar, bool isRoot, string indent)
    {
        sb.AppendLine();
        string propVar = n.FieldName + "Prop";
        sb.Append(indent).Append("var ").Append(propVar).Append(" = ").Append(sourceObjectVar)
          .Append(".RequireProperty(\"").Append(EscapeForCsString(n.JsonKey)).AppendLine("\");");
        sb.Append(indent).Append("var ").Append(n.FieldName).Append("Obj = ").Append(propVar).AppendLine(".Value as JsonSourceObject");
        sb.Append(indent).Append("    ?? throw new JsonParseException(\"Expected JSON object at '")
          .Append(EscapeForCsString(n.JsonKey)).AppendLine("'.\");");

        string pathExpr = isRoot
            ? ("\"" + n.JsonPointerSegment + "\"")
            : ("_pathPrefix + \"" + n.JsonPointerSegment + "\"");

        sb.Append(indent).Append("_").Append(n.FieldName).Append(" = new ").Append(n.TypeName).Append("(_ctx, ")
          .Append(pathExpr).Append(", ").Append(n.FieldName).AppendLine("Obj);");
    }

    // ── Collection bindings ──────────────────────────────────────────────────

    private sealed class CollectionBinding
    {
        public CollectionBinding(
            string jsonKey,
            string propertyName,
            string fieldName,
            string itemTypeName,
            JsonGenCollection collection)
        {
            JsonKey = jsonKey;
            PropertyName = propertyName;
            FieldName = fieldName;
            ItemTypeName = itemTypeName;
            Collection = collection;
            JsonPointerSegment = JsonPointerEscaper.Escape(jsonKey);
        }

        public string JsonKey { get; }
        public string PropertyName { get; }
        public string FieldName { get; }
        public string ItemTypeName { get; }
        public JsonGenCollection Collection { get; }
        public string JsonPointerSegment { get; }
    }

    private static void EmitCollectionCtorAssignment(StringBuilder sb, CollectionBinding c, string sourceObjectVar, bool isRoot, string indent)
    {
        sb.AppendLine();
        string propVar = c.FieldName + "Prop";
        string arrVar = c.FieldName + "Arr";
        string listVar = "list_" + c.FieldName;
        string idxVar = "idx_" + c.FieldName;
        string itemNodeVar = "node_" + c.FieldName;

        sb.Append(indent).Append("var ").Append(propVar).Append(" = ").Append(sourceObjectVar)
          .Append(".RequireProperty(\"").Append(EscapeForCsString(c.JsonKey)).AppendLine("\");");
        sb.Append(indent).Append("var ").Append(arrVar).Append(" = ").Append(propVar).AppendLine(".Value as JsonSourceArray");
        sb.Append(indent).Append("    ?? throw new JsonParseException(\"Expected JSON array at '")
          .Append(EscapeForCsString(c.JsonKey)).AppendLine("'.\");");

        sb.Append(indent).Append("var ").Append(listVar)
          .Append(" = new System.Collections.Generic.List<").Append(c.ItemTypeName).AppendLine(">();");

        if (c.Collection.ItemKind == JsonGenItemKind.Primitive)
        {
            sb.Append(indent).Append("foreach (JsonSourceNode ").Append(itemNodeVar).Append(" in ")
              .Append(arrVar).AppendLine(".Items)");
            sb.Append(indent).AppendLine("{");
            string readExpr = PrimitiveItemReadExpr(c.Collection.PrimitiveItemKind!.Value, itemNodeVar);
            sb.Append(indent).Append("    ").Append(listVar).Append(".Add(").Append(readExpr).AppendLine(");");
            sb.Append(indent).AppendLine("}");
        }
        else
        {
            // Object items. The item-path prefix is "<parent>/<index>", so we
            // pre-bake the trailing slash into a single literal — both nicer to
            // read in the generated output and one less concat at runtime.
            string itemPrefixLiteral = "\"" + c.JsonPointerSegment + "/\"";
            string itemPrefixExpr = isRoot
                ? itemPrefixLiteral
                : "_pathPrefix + " + itemPrefixLiteral;

            sb.Append(indent).Append("for (var ").Append(idxVar).Append(" = 0; ")
              .Append(idxVar).Append(" < ").Append(arrVar).Append(".Items.Count; ").Append(idxVar).AppendLine("++)")
              .Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(arrVar).Append(".Items[").Append(idxVar)
              .Append("] is not JsonSourceObject ").Append(itemNodeVar).AppendLine(")")
              .Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        throw new JsonParseException(\"Expected JSON object at '\" + ")
              .Append(itemPrefixExpr).Append(" + ").Append(idxVar).AppendLine(" + \"'.\");");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).Append("    ").Append(listVar)
              .Append(".Add(new ").Append(c.ItemTypeName).Append("(_ctx, ")
              .Append(itemPrefixExpr).Append(" + ").Append(idxVar).Append(", ").Append(itemNodeVar).AppendLine("));");
            sb.Append(indent).AppendLine("}");
        }

        sb.Append(indent).Append("_").Append(c.FieldName).Append(" = ").Append(listVar).AppendLine(";");
    }

    // ── Recursive nested-type emission ───────────────────────────────────────

    /// <summary>
    /// Emits all child object types declared by <paramref name="parent"/>.
    /// <paramref name="classIndent"/> is the indent of the <c>partial class</c>
    /// header (i.e. of the enclosing scope's class members), and grows by four
    /// spaces per level of nesting.
    /// </summary>
    private static void EmitNestedTypesRecursive(StringBuilder sb, JsonGenObject parent, string classIndent)
    {
        foreach (JsonGenNestedObject nested in parent.NestedObjects)
        {
            EmitChildClass(sb, NestedObjectTypeName(nested.Name), nested.Object, classIndent);
        }

        foreach (JsonGenCollection coll in parent.Collections)
        {
            if (coll.ItemKind == JsonGenItemKind.Object && coll.ObjectItem is not null)
            {
                // Class name must agree with the binding's resolved item type
                // (Items → Item, Books → Book, Data → DataItem). The collection
                // property occupies the plural slot, so the item class needs a
                // distinct name. Recompute with the same rule the emitter uses
                // when building the property's IReadOnlyList<T>.
                string propName = IdentifierSanitizer.ToPascalCase(coll.Name);
                string itemTypeName = SingularizeForItemType(coll.Name, propName);
                EmitChildClass(sb, itemTypeName, coll.ObjectItem, classIndent);
            }
        }
    }

    private static void EmitChildClass(StringBuilder sb, string className, JsonGenObject child, string classIndent)
    {
        string memberIndent = classIndent + "    ";
        string ctorIndent = memberIndent + "    ";

        sb.AppendLine();
        sb.Append(classIndent).Append("public sealed partial class ").AppendLine(className);
        sb.Append(classIndent).AppendLine("{");

        EmitObjectMembers(
            sb,
            obj: child,
            className: className,
            isRoot: false,
            classIndent: memberIndent,
            ctorIndent: ctorIndent,
            sourceObjectVar: "obj");

        // Recurse before closing the brace so child types are nested inside
        // this class rather than emitted as siblings of the root — see the
        // note in Emit().
        EmitNestedTypesRecursive(sb, child, memberIndent);

        sb.Append(classIndent).AppendLine("}");
    }

    // ── Scalar & writer mappings ─────────────────────────────────────────────

    private static string CSharpTypeFor(JsonGenScalarKind kind)
    {
        switch (kind)
        {
            case JsonGenScalarKind.String: return "string";
            case JsonGenScalarKind.NullableString: return "string?";
            case JsonGenScalarKind.Long: return "long";
            case JsonGenScalarKind.Decimal: return "decimal";
            case JsonGenScalarKind.Boolean: return "bool";
            default: throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    private static string ScalarReadExpr(JsonGenScalarKind kind, string nodeExpr)
    {
        switch (kind)
        {
            case JsonGenScalarKind.String:
                return "((JsonSourceString)" + nodeExpr + ").Value";
            case JsonGenScalarKind.NullableString:
                return nodeExpr + " is JsonSourceString s ? s.Value : null";
            case JsonGenScalarKind.Long:
                return "long.Parse(((JsonSourceNumber)" + nodeExpr + ").Literal, CultureInfo.InvariantCulture)";
            case JsonGenScalarKind.Decimal:
                return "decimal.Parse(((JsonSourceNumber)" + nodeExpr + ").Literal, CultureInfo.InvariantCulture)";
            case JsonGenScalarKind.Boolean:
                return "((JsonSourceBoolean)" + nodeExpr + ").Value";
            default: throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    private static string PrimitiveItemReadExpr(JsonGenScalarKind kind, string nodeVar)
    {
        switch (kind)
        {
            case JsonGenScalarKind.String:
                return "((JsonSourceString)" + nodeVar + ").Value";
            case JsonGenScalarKind.Long:
                return "long.Parse(((JsonSourceNumber)" + nodeVar + ").Literal, CultureInfo.InvariantCulture)";
            case JsonGenScalarKind.Decimal:
                return "decimal.Parse(((JsonSourceNumber)" + nodeVar + ").Literal, CultureInfo.InvariantCulture)";
            case JsonGenScalarKind.Boolean:
                return "((JsonSourceBoolean)" + nodeVar + ").Value";
            default:
                throw new InvalidOperationException("Unsupported primitive item kind.");
        }
    }

    private static string WriterCallFor(JsonGenScalarKind kind)
    {
        switch (kind)
        {
            case JsonGenScalarKind.String:
            case JsonGenScalarKind.NullableString:
                return "JsonValueWriter.WriteString(value)";
            case JsonGenScalarKind.Long:
                return "JsonValueWriter.WriteInt64(value)";
            case JsonGenScalarKind.Decimal:
                return "JsonValueWriter.WriteDecimal(value)";
            case JsonGenScalarKind.Boolean:
                return "JsonValueWriter.WriteBoolean(value)";
            default: throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    private static string DefaultValueExpr(JsonGenScalarKind kind)
    {
        switch (kind)
        {
            case JsonGenScalarKind.String: return "string.Empty";
            case JsonGenScalarKind.NullableString: return "null";
            case JsonGenScalarKind.Long: return "0L";
            case JsonGenScalarKind.Decimal: return "0m";
            case JsonGenScalarKind.Boolean: return "false";
            default: throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    // ── Misc helpers ─────────────────────────────────────────────────────────

    /// <summary>
    /// Returns a class name for a non-array nested object. The property in the
    /// parent already takes the natural Pascal-case slot (e.g. <c>Customer</c>),
    /// so the class needs a distinct name to avoid CS0102. We append <c>Type</c>
    /// — short and descriptive without colliding with realistic key names.
    /// </summary>
    private static string NestedObjectTypeName(string jsonKey)
    {
        return IdentifierSanitizer.ToPascalCase(jsonKey) + "Type";
    }

    /// <summary>
    /// Returns a class name for the items of a collection. Drops a trailing
    /// 's' to keep the type singular (Items → Item, Books → Book). If the
    /// depluralisation produces the same name as the property (e.g. JSON key
    /// 'data' → property 'Data', no trailing s), suffix with 'Item'.
    /// </summary>
    private static string SingularizeForItemType(string jsonKey, string propertyName)
    {
        string pascal = IdentifierSanitizer.ToPascalCase(jsonKey);
        if (pascal.Length > 1)
        {
            char last = pascal[pascal.Length - 1];
            if (last == 's' || last == 'S')
            {
                string singular = pascal.Substring(0, pascal.Length - 1);
                if (!string.Equals(singular, propertyName, StringComparison.Ordinal))
                {
                    return singular;
                }
            }
        }

        return string.Equals(pascal, propertyName, StringComparison.Ordinal)
            ? propertyName + "Item"
            : pascal;
    }

    private static string MakeUnique(string baseName, HashSet<string> usedNames)
    {
        if (string.IsNullOrEmpty(baseName))
        {
            baseName = "_Field";
        }

        if (usedNames.Add(baseName))
        {
            return baseName;
        }

        var n = 2;
        while (true)
        {
            string candidate = baseName + n.ToString();
            if (usedNames.Add(candidate))
            {
                return candidate;
            }
            n++;
        }
    }

    private static string ToCamel(string pascal)
    {
        if (string.IsNullOrEmpty(pascal))
        {
            return pascal;
        }

        var start = 0;
        while (start < pascal.Length && pascal[start] == '_')
        {
            start++;
        }

        if (start >= pascal.Length)
        {
            return pascal;
        }

        var sb = new StringBuilder(pascal.Length);
        sb.Append(pascal, 0, start);
        sb.Append(char.ToLowerInvariant(pascal[start]));
        if (pascal.Length > start + 1)
        {
            sb.Append(pascal, start + 1, pascal.Length - start - 1);
        }
        return sb.ToString();
    }

    private static string EscapeForCsString(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }
}
