using System;
using System.Collections.Generic;
using System.Text;

namespace Structura.Generator;

/// <summary>
/// Generates the C# source text for a document model class from the list of
/// root-level properties extracted by <see cref="GeneratorJsonParser"/>.
/// Non-scalar properties (objects, arrays) are silently skipped — V1 scope.
/// </summary>
internal static class ModelEmitter
{
    public static string Emit(string className, List<GenProperty> properties)
    {
        // Resolve C# identifier names and JSON Pointer paths for every scalar.
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var scalars = new List<ScalarInfo>();

        foreach (GenProperty? prop in properties)
        {
            if (!TryGetScalarInfo(prop, usedNames, out ScalarInfo? info))
            {
                continue;
            }

            scalars.Add(info!);
        }

        var sb = new StringBuilder(4096);

        // ── File header ──────────────────────────────────────────────────────
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Structura.Runtime;");
        sb.AppendLine("using Structura.Runtime.Json;");
        sb.AppendLine();
        sb.AppendLine("namespace Structura.Generated;");
        sb.AppendLine();

        // ── Class declaration ─────────────────────────────────────────────────
        sb.Append("public sealed partial class ").Append(className);
        sb.AppendLine();
        sb.Append("    : IStructuraJsonDocument<").Append(className).AppendLine(">, IStructuraDocument");
        sb.AppendLine("{");

        // ── Context field ─────────────────────────────────────────────────────
        sb.AppendLine("    private readonly StructuraDocumentContext _ctx;");

        // ── Span + value fields ───────────────────────────────────────────────
        foreach (ScalarInfo? s in scalars)
        {
            sb.AppendLine();
            sb.Append("    private readonly TextSpan _").Append(s.CamelName).AppendLine("ValueSpan;");
            sb.Append("    private ").Append(s.CSharpType).Append(" _").Append(s.CamelName).AppendLine(";");
        }

        // ── Private constructor ───────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    private ").Append(className).AppendLine("(string source, JsonSourceObject root)");
        sb.AppendLine("    {");
        sb.AppendLine("        _ctx = new StructuraDocumentContext(source);");
        sb.AppendLine();

        foreach (ScalarInfo? s in scalars)
        {
            EmitCtorAssignment(sb, s);
        }

        sb.AppendLine("    }");

        // ── ParseFromJson ─────────────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    public static ").Append(className).AppendLine(" ParseFromJson(string source)");
        sb.AppendLine("    {");
        sb.AppendLine("        var root = JsonSourceParser.Parse(source);");
        sb.AppendLine("        if (root is not JsonSourceObject obj)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new JsonParseException(\"Expected JSON object at root.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        return new ").Append(className).AppendLine("(source, obj);");
        sb.AppendLine("    }");

        // ── Properties ────────────────────────────────────────────────────────
        foreach (ScalarInfo? s in scalars)
        {
            sb.AppendLine();
            sb.Append("    public ").Append(s.CSharpType).Append(' ').AppendLine(s.PascalName);
            sb.AppendLine("    {");
            sb.Append("        get => _").Append(s.CamelName).AppendLine(";");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.Append("            _").Append(s.CamelName).AppendLine(" = value;");
            sb.Append("            _ctx.Record(\"").Append(s.JsonPointer).Append("\", _").Append(s.CamelName)
              .Append("ValueSpan, ").Append(s.WriterCall).AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        // ── ToJson + interface implementations ────────────────────────────────
        sb.AppendLine();
        sb.AppendLine("    public string ToJson() => _ctx.ApplyEdits();");
        sb.AppendLine();
        sb.AppendLine("    string IStructuraDocument.OriginalText => _ctx.OriginalText;");
        sb.AppendLine("    string IStructuraDocument.CurrentText  => _ctx.ApplyEdits();");
        sb.AppendLine("    IReadOnlyList<DocumentChange> IStructuraDocument.Changes => _ctx.Changes;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static bool TryGetScalarInfo(
        GenProperty prop,
        HashSet<string> usedNames,
        out ScalarInfo? info)
    {
        info = null;

        string csharpType;
        string ctorExpr;
        string writerCall;

        switch (prop.Value)
        {
            case GenStringValue:
                csharpType  = "string";
                ctorExpr    = $"((JsonSourceString){PropVar(prop.Name)}.Value).Value";
                writerCall  = "JsonValueWriter.WriteString(value)";
                break;

            case GenNullValue:
                csharpType  = "string?";
                ctorExpr    = $"{PropVar(prop.Name)}.Value is JsonSourceString {CamelCase(prop.Name)}Str ? {CamelCase(prop.Name)}Str.Value : null";
                writerCall  = "JsonValueWriter.WriteString(value)";
                break;

            case GenLongValue:
                csharpType  = "long";
                ctorExpr    = $"long.Parse(((JsonSourceNumber){PropVar(prop.Name)}.Value).Literal, CultureInfo.InvariantCulture)";
                writerCall  = "JsonValueWriter.WriteInt64(value)";
                break;

            case GenDecimalValue:
                csharpType  = "decimal";
                ctorExpr    = $"decimal.Parse(((JsonSourceNumber){PropVar(prop.Name)}.Value).Literal, CultureInfo.InvariantCulture)";
                writerCall  = "JsonValueWriter.WriteDecimal(value)";
                break;

            case GenBoolValue:
                csharpType  = "bool";
                ctorExpr    = $"((JsonSourceBoolean){PropVar(prop.Name)}.Value).Value";
                writerCall  = "JsonValueWriter.WriteBoolean(value)";
                break;

            default:
                return false; // object / array → skip
        }

        string pascalName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        string camelName  = ToCamel(pascalName);

        info = new ScalarInfo(
            jsonKey:     prop.Name,
            pascalName:  pascalName,
            camelName:   camelName,
            csharpType:  csharpType,
            ctorExpr:    ctorExpr,
            writerCall:  writerCall,
            jsonPointer: JsonPointerEscaper.Escape(prop.Name));

        return true;
    }

    /// <summary>Local variable name for a <c>root.RequireProperty(key)</c> call.</summary>
    private static string PropVar(string jsonKey)
    {
        return CamelCase(jsonKey) + "Prop";
    }

    /// <summary>camelCase from a JSON key (used for local variable naming).</summary>
    private static string CamelCase(string jsonKey)
    {
        string pascal = IdentifierSanitizer.ToPascalCase(jsonKey);
        return ToCamel(pascal);
    }

    private static string ToCamel(string pascal)
    {
        if (string.IsNullOrEmpty(pascal))
        {
            return pascal;
        }

        // Preserve any leading '_' added for digit-starting identifiers.
        var start = 0;
        while (start < pascal.Length && pascal[start] == '_')
        {
            start++;
        }

        if (start >= pascal.Length)
        {
            return pascal;
        }

        var sb = new StringBuilder(pascal.Length);
        sb.Append(pascal, 0, start);
        sb.Append(char.ToLowerInvariant(pascal[start]));
        if (pascal.Length > start + 1)
        {
            sb.Append(pascal, start + 1, pascal.Length - start - 1);
        }

        return sb.ToString();
    }

    private static void EmitCtorAssignment(StringBuilder sb, ScalarInfo s)
    {
        string propVar = s.CamelName + "Prop";
        sb.Append("        var ").Append(propVar)
          .Append(" = root.RequireProperty(\"").Append(s.JsonKey).AppendLine("\");");
        sb.Append("        _").Append(s.CamelName).Append("ValueSpan = ").Append(propVar).AppendLine(".ValueSpan;");
        sb.Append("        _").Append(s.CamelName).Append(" = ").Append(s.CtorExpr).AppendLine(";");
        sb.AppendLine();
    }

    // ── Internal record ───────────────────────────────────────────────────────

    private sealed class ScalarInfo
    {
        public ScalarInfo(
            string jsonKey,
            string pascalName,
            string camelName,
            string csharpType,
            string ctorExpr,
            string writerCall,
            string jsonPointer)
        {
            JsonKey     = jsonKey;
            PascalName  = pascalName;
            CamelName   = camelName;
            CSharpType  = csharpType;
            CtorExpr    = ctorExpr;
            WriterCall  = writerCall;
            JsonPointer = jsonPointer;
        }

        public string JsonKey     { get; }
        public string PascalName  { get; }
        public string CamelName   { get; }
        public string CSharpType  { get; }
        public string CtorExpr    { get; }
        public string WriterCall  { get; }
        public string JsonPointer { get; }
    }
}
