using System;
using System.Collections.Generic;
using System.Text;

namespace Structura.Generator;

/// <summary>
/// Generates the C# source text for an XML-backed document model — direct
/// shape-mirror of <see cref="ModelEmitter"/> for JSON. Per scalar property
/// the emitter captures the patchable span (<c>InnerSpan</c> for elements,
/// <c>ValueSpan</c> for attributes) and wires the setter to
/// <see cref="StructuraDocumentContext.Record"/> with the appropriate
/// <c>XmlValueWriter</c> call.
/// </summary>
internal static class XmlModelEmitter
{
    public static string Emit(string className, XmlRootInfo info)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var scalars = new List<XmlScalarInfo>();

        foreach (XmlGenProperty prop in info.Scalars)
        {
            scalars.Add(BuildScalar(prop, usedNames));
        }

        var sb = new StringBuilder(4096);

        // ── File header ──────────────────────────────────────────────────────
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Structura.Runtime;");
        sb.AppendLine("using Structura.Runtime.Xml;");
        sb.AppendLine();
        sb.AppendLine("namespace Structura.Generated;");
        sb.AppendLine();

        // ── Class declaration ────────────────────────────────────────────────
        sb.Append("public sealed partial class ").Append(className);
        sb.AppendLine();
        sb.Append("    : IStructuraXmlDocument<").Append(className).AppendLine(">, IStructuraDocument");
        sb.AppendLine("{");

        // ── Context field ────────────────────────────────────────────────────
        sb.AppendLine("    private readonly StructuraDocumentContext _ctx;");

        // ── Span + value fields ──────────────────────────────────────────────
        foreach (XmlScalarInfo s in scalars)
        {
            sb.AppendLine();
            sb.Append("    private readonly TextSpan _").Append(s.CamelName).AppendLine("ValueSpan;");
            sb.Append("    private ").Append(s.CSharpType).Append(" _").Append(s.CamelName).AppendLine(";");
        }

        // ── Private constructor ──────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    private ").Append(className).AppendLine("(string source, XmlSourceElement root)");
        sb.AppendLine("    {");
        sb.AppendLine("        _ctx = new StructuraDocumentContext(source);");
        sb.AppendLine();

        foreach (XmlScalarInfo s in scalars)
        {
            EmitCtorAssignment(sb, s);
        }

        sb.AppendLine("    }");

        // ── ParseFromXml ─────────────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    public static ").Append(className).AppendLine(" ParseFromXml(string source)");
        sb.AppendLine("    {");
        sb.AppendLine("        XmlSourceElement root = XmlSourceParser.Parse(source);");
        sb.Append("        if (!string.Equals(root.Name, \"")
          .Append(EscapeForCsString(info.RootName))
          .AppendLine("\", System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.Append("            throw new XmlParseException($\"Expected <")
          .Append(EscapeForCsString(info.RootName))
          .AppendLine("> at root, found <{root.Name}>.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        return new ").Append(className).AppendLine("(source, root);");
        sb.AppendLine("    }");

        // ── Properties ───────────────────────────────────────────────────────
        foreach (XmlScalarInfo s in scalars)
        {
            sb.AppendLine();
            sb.Append("    public ").Append(s.CSharpType).Append(' ').AppendLine(s.PascalName);
            sb.AppendLine("    {");
            sb.Append("        get => _").Append(s.CamelName).AppendLine(";");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.Append("            _").Append(s.CamelName).AppendLine(" = value;");
            sb.Append("            _ctx.Record(\"").Append(s.Path).Append("\", _").Append(s.CamelName)
              .Append("ValueSpan, ").Append(s.WriterCall).AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        // ── ToXml + interface implementations ────────────────────────────────
        sb.AppendLine();
        sb.AppendLine("    public string ToXml()");
        sb.AppendLine("    {");
        sb.AppendLine("        return _ctx.ApplyEdits();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    string IStructuraDocument.OriginalText => _ctx.OriginalText;");
        sb.AppendLine("    string IStructuraDocument.CurrentText => _ctx.ApplyEdits();");
        sb.AppendLine("    IReadOnlyList<DocumentChange> IStructuraDocument.Changes => _ctx.Changes;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static XmlScalarInfo BuildScalar(XmlGenProperty prop, HashSet<string> usedNames)
    {
        string csharpType;
        string spanExpr;
        string ctorExpr;
        string writerCall;
        string lookupExpr;

        string pascalName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        string camelName = ToCamel(pascalName);
        string textVar = camelName + "Text";

        if (prop.IsAttribute)
        {
            lookupExpr = $"root.RequireAttribute(\"{EscapeForCsString(prop.Name)}\")";
            spanExpr = ".ValueSpan";
            // Attribute decoded value is at .Value (no entity wrapping needed).
            switch (prop.Kind)
            {
                case XmlGenScalarKind.String:
                    csharpType = "string";
                    ctorExpr = $"{camelName}Attr.Value";
                    writerCall = "XmlValueWriter.WriteAttributeValue(value)";
                    break;
                case XmlGenScalarKind.Long:
                    csharpType = "long";
                    ctorExpr = $"long.Parse({camelName}Attr.Value, CultureInfo.InvariantCulture)";
                    writerCall = "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteInt64(value))";
                    break;
                case XmlGenScalarKind.Decimal:
                    csharpType = "decimal";
                    ctorExpr = $"decimal.Parse({camelName}Attr.Value, CultureInfo.InvariantCulture)";
                    writerCall = "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteDecimal(value))";
                    break;
                case XmlGenScalarKind.Boolean:
                    csharpType = "bool";
                    ctorExpr = $"bool.Parse({camelName}Attr.Value)";
                    writerCall = "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteBoolean(value))";
                    break;
                default:
                    throw new InvalidOperationException("Unknown scalar kind.");
            }
            string path = "/@" + prop.Name;
            return new XmlScalarInfo(
                xmlName: prop.Name,
                pascalName: pascalName,
                camelName: camelName,
                csharpType: csharpType,
                lookupExpr: lookupExpr,
                lookupVarName: camelName + "Attr",
                spanExpr: spanExpr,
                ctorExpr: ctorExpr,
                writerCall: writerCall,
                path: path,
                textExtractionExpr: null);
        }
        else
        {
            lookupExpr = $"root.RequireElement(\"{EscapeForCsString(prop.Name)}\")";
            spanExpr = ".InnerSpan";
            // Element pure-text content is the first child as XmlSourceText.
            string textExtraction = $"((XmlSourceText){camelName}El.Children[0]).Value";
            switch (prop.Kind)
            {
                case XmlGenScalarKind.String:
                    csharpType = "string";
                    ctorExpr = textExtraction;
                    writerCall = "XmlValueWriter.WriteElementText(value)";
                    break;
                case XmlGenScalarKind.Long:
                    csharpType = "long";
                    ctorExpr = $"long.Parse({textExtraction}, CultureInfo.InvariantCulture)";
                    writerCall = "XmlValueWriter.WriteInt64(value)";
                    break;
                case XmlGenScalarKind.Decimal:
                    csharpType = "decimal";
                    ctorExpr = $"decimal.Parse({textExtraction}, CultureInfo.InvariantCulture)";
                    writerCall = "XmlValueWriter.WriteDecimal(value)";
                    break;
                case XmlGenScalarKind.Boolean:
                    csharpType = "bool";
                    ctorExpr = $"bool.Parse({textExtraction})";
                    writerCall = "XmlValueWriter.WriteBoolean(value)";
                    break;
                default:
                    throw new InvalidOperationException("Unknown scalar kind.");
            }
            string path = "/" + prop.Name;
            return new XmlScalarInfo(
                xmlName: prop.Name,
                pascalName: pascalName,
                camelName: camelName,
                csharpType: csharpType,
                lookupExpr: lookupExpr,
                lookupVarName: camelName + "El",
                spanExpr: spanExpr,
                ctorExpr: ctorExpr,
                writerCall: writerCall,
                path: path,
                textExtractionExpr: textExtraction);
        }
    }

    private static void EmitCtorAssignment(StringBuilder sb, XmlScalarInfo s)
    {
        sb.Append("        var ").Append(s.LookupVarName)
          .Append(" = ").Append(s.LookupExpr).AppendLine(";");
        sb.Append("        _").Append(s.CamelName).Append("ValueSpan = ")
          .Append(s.LookupVarName).Append(s.SpanExpr).AppendLine(";");
        sb.Append("        _").Append(s.CamelName).Append(" = ").Append(s.CtorExpr).AppendLine(";");
        sb.AppendLine();
    }

    private static string ToCamel(string pascal)
    {
        if (string.IsNullOrEmpty(pascal))
        {
            return pascal;
        }

        int start = 0;
        while (start < pascal.Length && pascal[start] == '_')
        {
            start++;
        }

        if (start >= pascal.Length)
        {
            return pascal;
        }

        var sb = new StringBuilder(pascal.Length);
        sb.Append(pascal, 0, start);
        sb.Append(char.ToLowerInvariant(pascal[start]));
        if (pascal.Length > start + 1)
        {
            sb.Append(pascal, start + 1, pascal.Length - start - 1);
        }

        return sb.ToString();
    }

    private static string EscapeForCsString(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                default:
                    sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }

    private sealed class XmlScalarInfo
    {
        public XmlScalarInfo(
            string xmlName,
            string pascalName,
            string camelName,
            string csharpType,
            string lookupExpr,
            string lookupVarName,
            string spanExpr,
            string ctorExpr,
            string writerCall,
            string path,
            string? textExtractionExpr)
        {
            XmlName = xmlName;
            PascalName = pascalName;
            CamelName = camelName;
            CSharpType = csharpType;
            LookupExpr = lookupExpr;
            LookupVarName = lookupVarName;
            SpanExpr = spanExpr;
            CtorExpr = ctorExpr;
            WriterCall = writerCall;
            Path = path;
            TextExtractionExpr = textExtractionExpr;
        }

        public string XmlName { get; }
        public string PascalName { get; }
        public string CamelName { get; }
        public string CSharpType { get; }
        public string LookupExpr { get; }
        public string LookupVarName { get; }
        public string SpanExpr { get; }
        public string CtorExpr { get; }
        public string WriterCall { get; }
        public string Path { get; }
        public string? TextExtractionExpr { get; }
    }
}
