using System;
using System.Collections.Generic;
using System.Text;

namespace Structura.Generator;

/// <summary>
/// Generates the C# source text for an XML-backed document model.
/// Handles root scalars, four collection shapes (wrapper-as-nested-object,
/// wrapper-flat, sibling-group, pure-text-leaf), recursive item types,
/// and heterogeneous-item field-union with throwing setters for absent
/// source spans.
/// </summary>
internal static class XmlModelEmitter
{
    public static string Emit(string className, XmlRootInfo info)
    {
        var sb = new StringBuilder(8192);

        // ── File header ──────────────────────────────────────────────────────
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Structura.Runtime;");
        sb.AppendLine("using Structura.Runtime.Xml;");
        sb.AppendLine();
        sb.AppendLine("namespace Structura.Generated;");
        sb.AppendLine();

        // ── Class declaration ────────────────────────────────────────────────
        sb.Append("public sealed partial class ").Append(className);
        sb.AppendLine();
        sb.Append("    : IStructuraXmlDocument<").Append(className).AppendLine(">, IStructuraDocument");
        sb.AppendLine("{");

        // ── Context field ────────────────────────────────────────────────────
        sb.AppendLine("    private readonly StructuraDocumentContext _ctx;");

        var usedRootNames = new HashSet<string>(StringComparer.Ordinal);
        var rootScalars = new List<RootScalar>();
        foreach (XmlGenProperty prop in info.Scalars)
        {
            rootScalars.Add(BuildRootScalar(prop, usedRootNames));
        }

        // Reserve collection property names so they don't collide with scalars.
        var rootCollectionNames = new List<string>();
        foreach (XmlGenCollection coll in info.Collections)
        {
            string unique = MakeUnique(coll.CSharpPropertyName, usedRootNames);
            rootCollectionNames.Add(unique);
        }

        // Reserve nested-object property names alongside scalars/collections.
        var rootNestedBindings = new List<NestedObjectBinding>();
        foreach (XmlGenNestedObject nested in info.NestedObjects)
        {
            string propName = MakeUnique(IdentifierSanitizer.ToPascalCase(nested.XmlElementName), usedRootNames);
            rootNestedBindings.Add(new NestedObjectBinding(
                xmlElementName: nested.XmlElementName,
                propertyName: propName,
                fieldName: ToCamel(propName),
                typeName: NestedObjectTypeName(nested.XmlElementName)));
        }

        // ── Span + value fields (root scalars) ───────────────────────────────
        foreach (RootScalar s in rootScalars)
        {
            sb.AppendLine();
            sb.Append("    private readonly TextSpan _").Append(s.CamelName).AppendLine("ValueSpan;");
            sb.Append("    private ").Append(s.CSharpType).Append(" _").Append(s.CamelName).AppendLine(";");
        }

        // ── Backing fields for collections ───────────────────────────────────
        for (var i = 0; i < info.Collections.Count; i++)
        {
            XmlGenCollection coll = info.Collections[i];
            string propName = rootCollectionNames[i];
            sb.AppendLine();
            EmitCollectionBackingField(sb, coll, propName);
        }

        // ── Backing fields for nested objects ────────────────────────────────
        foreach (NestedObjectBinding n in rootNestedBindings)
        {
            sb.AppendLine();
            sb.Append("    private readonly ").Append(n.TypeName).Append(" _")
              .Append(n.FieldName).AppendLine(";");
        }

        // ── Private constructor ──────────────────────────────────────────────
        sb.AppendLine();
        sb.Append("    private ").Append(className).AppendLine("(string source, XmlSourceElement root)");
        sb.AppendLine("    {");
        sb.AppendLine("        _ctx = new StructuraDocumentContext(source);");
        sb.AppendLine();

        foreach (RootScalar s in rootScalars)
        {
            EmitRootScalarCtor(sb, s);
        }

        for (var i = 0; i < info.Collections.Count; i++)
        {
            EmitCollectionCtor(
                sb,
                coll: info.Collections[i],
                csharpPropertyName: rootCollectionNames[i],
                sourceElementVar: "root",
                parentPathPrefixExpr: "\"\"",
                contextExpr: "_ctx",
                indent: "        ");
        }

        foreach (NestedObjectBinding n in rootNestedBindings)
        {
            sb.AppendLine();
            sb.Append("        var ").Append(n.FieldName).Append("El = root.RequireElement(\"")
              .Append(EscapeForCsString(n.XmlElementName)).AppendLine("\");");
            sb.Append("        _").Append(n.FieldName).Append(" = new ").Append(n.TypeName)
              .Append("(_ctx, \"/").Append(n.PropertyName).Append("\", ")
              .Append(n.FieldName).AppendLine("El);");
        }

        sb.AppendLine("    }");

        // ── ParseFromXml (literal-root validation + wrapper-chain descent) ──
        sb.AppendLine();
        sb.Append("    public static ").Append(className).AppendLine(" ParseFromXml(string source)");
        sb.AppendLine("    {");
        sb.AppendLine("        XmlSourceElement root = XmlSourceParser.Parse(source);");
        sb.Append("        if (!string.Equals(root.Name, \"")
          .Append(EscapeForCsString(info.RootName))
          .AppendLine("\", System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.Append("            throw new XmlParseException($\"Expected <")
          .Append(EscapeForCsString(info.RootName))
          .AppendLine("> at root, found <{root.Name}>.\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        if (info.WrapperChain.Count == 0)
        {
            sb.Append("        return new ").Append(className).AppendLine("(source, root);");
        }
        else
        {
            sb.Append("        XmlSourceElement effectiveRoot = root");
            foreach (string wrapperName in info.WrapperChain)
            {
                sb.Append(".RequireElement(\"")
                  .Append(EscapeForCsString(wrapperName))
                  .Append("\")");
            }
            sb.AppendLine(";");
            sb.Append("        return new ").Append(className).AppendLine("(source, effectiveRoot);");
        }
        sb.AppendLine("    }");

        // ── Root scalar properties ───────────────────────────────────────────
        foreach (RootScalar s in rootScalars)
        {
            EmitRootScalarProperty(sb, s);
        }

        // ── Collection properties ────────────────────────────────────────────
        for (var i = 0; i < info.Collections.Count; i++)
        {
            EmitCollectionProperty(sb, info.Collections[i], rootCollectionNames[i]);
        }

        // ── Nested-object properties ─────────────────────────────────────────
        foreach (NestedObjectBinding n in rootNestedBindings)
        {
            sb.AppendLine();
            sb.Append("    public ").Append(n.TypeName).Append(' ').Append(n.PropertyName)
              .Append(" => _").Append(n.FieldName).AppendLine(";");
        }

        // ── ToXml + interface implementations ────────────────────────────────
        sb.AppendLine();
        sb.AppendLine("    public string ToXml()");
        sb.AppendLine("    {");
        sb.AppendLine("        return _ctx.ApplyEdits();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    string IStructuraDocument.OriginalText => _ctx.OriginalText;");
        sb.AppendLine("    string IStructuraDocument.CurrentText => _ctx.ApplyEdits();");
        sb.AppendLine("    IReadOnlyList<DocumentChange> IStructuraDocument.Changes => _ctx.Changes;");

        // ── Nested types (wrapper + item + nested-object) ────────────────────
        foreach (XmlGenCollection coll in info.Collections)
        {
            EmitNestedTypesForCollection(sb, coll);
        }

        foreach (XmlGenNestedObject nested in info.NestedObjects)
        {
            EmitNestedObjectType(sb, nested);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Nested-type emission ─────────────────────────────────────────────────

    /// <summary>
    /// Wrapper TYPE names get a <c>Group</c> suffix so they don't collide with
    /// the parent's property name (<c>BlrwblSampleXml.DespatchAdviceLogisticUnitLineItem</c>
    /// the property vs <c>BlrwblSampleXml.DespatchAdviceLogisticUnitLineItemGroup</c>
    /// the type). The user never types the type name explicitly — they go through
    /// <c>var</c>.
    /// </summary>
    private static string WrapperTypeName(XmlGenCollection coll)
    {
        return ClassNameDeriver.Derive(coll.WrapperElementName!) + "Group";
    }

    /// <summary>
    /// Nested-object TYPE names get a <c>Type</c> suffix for the same reason
    /// as wrappers — the parent already exposes the natural Pascal-case slot
    /// as a property (<c>waybill.Document</c>), so the class needs a distinct
    /// name (<c>DocumentType</c>) to avoid CS0102. <see cref="IdentifierSanitizer"/>
    /// rather than <see cref="ClassNameDeriver"/> because element names like
    /// <c>meta:info</c> contain colons that <see cref="ClassNameDeriver"/>
    /// preserves but C# does not allow.
    /// </summary>
    private static string NestedObjectTypeName(string xmlElementName)
    {
        return IdentifierSanitizer.ToPascalCase(xmlElementName) + "Type";
    }

    private static void EmitNestedTypesForCollection(StringBuilder sb, XmlGenCollection coll)
    {
        if (coll.Style == XmlGenCollectionStyle.Wrapper)
        {
            // Emit the wrapper class containing only the inner collection.
            string wrapperTypeName = WrapperTypeName(coll);

            // Inner collection property name is the pluralized ITEM element name
            // ("LineItems"), NOT the parent's property name ("DespatchAdviceLogisticUnitLineItem").
            string innerPropName = Pluralize(coll.ItemElementName);

            sb.AppendLine();
            sb.Append("    public sealed partial class ").AppendLine(wrapperTypeName);
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly StructuraDocumentContext _ctx;");
            sb.AppendLine("        private readonly string _pathPrefix;");

            sb.AppendLine();
            sb.Append("        private readonly IReadOnlyList<")
              .Append(coll.ItemTypeName).Append("> _")
              .Append(ToCamel(innerPropName)).AppendLine(";");

            // Wrapper constructor: iterate element.Children matching ItemElementName,
            // build items (or string leaves).
            sb.AppendLine();
            sb.Append("        internal ").Append(wrapperTypeName)
              .AppendLine("(StructuraDocumentContext ctx, string pathPrefix, XmlSourceElement element)");
            sb.AppendLine("        {");
            sb.AppendLine("            _ctx = ctx;");
            sb.AppendLine("            _pathPrefix = pathPrefix;");
            EmitCollectionItemsInitFromWrapper(
                sb,
                coll: coll,
                csharpPropertyName: innerPropName,
                wrapperVarName: "element",
                parentPathPrefixExpr: "_pathPrefix",
                contextExpr: "_ctx",
                indent: "            ");
            sb.AppendLine("        }");

            // Wrapper property (the inner collection):
            sb.AppendLine();
            sb.Append("        public IReadOnlyList<")
              .Append(coll.ItemTypeName).Append("> ").Append(innerPropName)
              .Append(" => _").Append(ToCamel(innerPropName)).AppendLine(";");

            sb.AppendLine("    }");
        }

        // Emit the item class itself (for non-pure-text-leaf collections).
        if (!coll.ItemIsPureTextLeaf)
        {
            EmitItemType(sb, coll.Item!);
        }
    }

    private static string Pluralize(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        if (name[name.Length - 1] == 's' || name[name.Length - 1] == 'S')
        {
            return ClassNameDeriver.Derive(name);
        }
        return ClassNameDeriver.Derive(name) + "s";
    }

    private static void EmitItemType(StringBuilder sb, ItemTypeInfo item)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var itemScalars = new List<ItemScalar>();
        foreach (XmlGenProperty prop in item.Scalars)
        {
            itemScalars.Add(BuildItemScalar(prop, usedNames));
        }

        var itemCollectionNames = new List<string>();
        foreach (XmlGenCollection inner in item.Collections)
        {
            string unique = MakeUnique(inner.CSharpPropertyName, usedNames);
            itemCollectionNames.Add(unique);
        }

        var itemNestedBindings = new List<NestedObjectBinding>();
        foreach (XmlGenNestedObject inner in item.NestedObjects)
        {
            string propName = MakeUnique(IdentifierSanitizer.ToPascalCase(inner.XmlElementName), usedNames);
            itemNestedBindings.Add(new NestedObjectBinding(
                xmlElementName: inner.XmlElementName,
                propertyName: propName,
                fieldName: ToCamel(propName),
                typeName: NestedObjectTypeName(inner.XmlElementName)));
        }

        sb.AppendLine();
        sb.Append("    public sealed partial class ").AppendLine(item.TypeName);
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly StructuraDocumentContext _ctx;");
        sb.AppendLine("        private readonly string _pathPrefix;");

        // Span + value + IsPresent fields per item scalar.
        foreach (ItemScalar s in itemScalars)
        {
            sb.AppendLine();
            sb.Append("        private readonly bool _").Append(s.CamelName).AppendLine("IsPresent;");
            sb.Append("        private readonly TextSpan _").Append(s.CamelName).AppendLine("ValueSpan;");
            sb.Append("        private ").Append(s.CSharpType).Append(" _").Append(s.CamelName).AppendLine(";");
        }

        // Backing fields for nested collections inside the item.
        for (var i = 0; i < item.Collections.Count; i++)
        {
            sb.AppendLine();
            EmitCollectionBackingField(sb, item.Collections[i], itemCollectionNames[i], indent: "        ");
        }

        // Backing fields for nested objects inside the item.
        foreach (NestedObjectBinding n in itemNestedBindings)
        {
            sb.AppendLine();
            sb.Append("        private readonly ").Append(n.TypeName).Append(" _")
              .Append(n.FieldName).AppendLine(";");
        }

        // Item constructor.
        sb.AppendLine();
        sb.Append("        internal ").Append(item.TypeName)
          .AppendLine("(StructuraDocumentContext ctx, string pathPrefix, XmlSourceElement element)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ctx = ctx;");
        sb.AppendLine("            _pathPrefix = pathPrefix;");

        foreach (ItemScalar s in itemScalars)
        {
            EmitItemScalarCtor(sb, s);
        }

        for (var i = 0; i < item.Collections.Count; i++)
        {
            EmitCollectionCtor(
                sb,
                coll: item.Collections[i],
                csharpPropertyName: itemCollectionNames[i],
                sourceElementVar: "element",
                parentPathPrefixExpr: "_pathPrefix",
                contextExpr: "_ctx",
                indent: "            ",
                optional: true);
        }

        foreach (NestedObjectBinding n in itemNestedBindings)
        {
            sb.AppendLine();
            sb.Append("            var ").Append(n.FieldName).Append("El = element.RequireElement(\"")
              .Append(EscapeForCsString(n.XmlElementName)).AppendLine("\");");
            sb.Append("            _").Append(n.FieldName).Append(" = new ").Append(n.TypeName)
              .Append("(_ctx, _pathPrefix + \"/").Append(n.PropertyName).Append("\", ")
              .Append(n.FieldName).AppendLine("El);");
        }

        sb.AppendLine("        }");

        // Item scalar properties.
        foreach (ItemScalar s in itemScalars)
        {
            EmitItemScalarProperty(sb, s, item.XmlElementName);
        }

        // Inner collection properties.
        for (var i = 0; i < item.Collections.Count; i++)
        {
            EmitCollectionProperty(sb, item.Collections[i], itemCollectionNames[i], indent: "        ");
        }

        // Item-level nested-object properties.
        foreach (NestedObjectBinding n in itemNestedBindings)
        {
            sb.AppendLine();
            sb.Append("        public ").Append(n.TypeName).Append(' ').Append(n.PropertyName)
              .Append(" => _").Append(n.FieldName).AppendLine(";");
        }

        sb.AppendLine("    }");

        // Recurse into nested collections and nested-object types.
        foreach (XmlGenCollection inner in item.Collections)
        {
            EmitNestedTypesForCollection(sb, inner);
        }

        foreach (XmlGenNestedObject inner in item.NestedObjects)
        {
            EmitNestedObjectType(sb, inner);
        }
    }

    // ── Collection emission ──────────────────────────────────────────────────

    private static void EmitCollectionBackingField(
        StringBuilder sb,
        XmlGenCollection coll,
        string csharpPropertyName,
        string indent = "    ")
    {
        if (coll.Style == XmlGenCollectionStyle.Wrapper)
        {
            // Wrapper-style: backing field is the wrapper instance (not a list).
            string wrapperTypeName = WrapperTypeName(coll);
            sb.Append(indent).Append("private readonly ")
              .Append(wrapperTypeName).Append(" _")
              .Append(ToCamel(csharpPropertyName)).AppendLine(";");
        }
        else
        {
            // Flat / SiblingGroup / pure-text-leaf: IReadOnlyList<TItem>.
            sb.Append(indent).Append("private readonly IReadOnlyList<")
              .Append(coll.ItemTypeName).Append("> _")
              .Append(ToCamel(csharpPropertyName)).AppendLine(";");
        }
    }

    private static void EmitCollectionCtor(
        StringBuilder sb,
        XmlGenCollection coll,
        string csharpPropertyName,
        string sourceElementVar,
        string parentPathPrefixExpr,
        string contextExpr,
        string indent,
        bool optional = false)
    {
        if (coll.Style == XmlGenCollectionStyle.Wrapper)
        {
            // Wrapper-style: instantiate the wrapper class. Wrapper's own
            // pathPrefix is parentPathPrefix + "/" + wrapperPropertyName.
            string wrapperTypeName = WrapperTypeName(coll);
            sb.AppendLine();
            sb.Append(indent).Append("var ").Append(ToCamel(csharpPropertyName))
              .Append("WrapperEl = ").Append(sourceElementVar)
              .Append(".RequireElement(\"").Append(EscapeForCsString(coll.WrapperElementName!))
              .AppendLine("\");");
            sb.Append(indent).Append("_").Append(ToCamel(csharpPropertyName))
              .Append(" = new ").Append(wrapperTypeName).Append("(")
              .Append(contextExpr).Append(", ")
              .Append(parentPathPrefixExpr).Append(" + \"/").Append(csharpPropertyName).Append("\", ")
              .Append(ToCamel(csharpPropertyName)).AppendLine("WrapperEl);");
        }
        else if (coll.Style == XmlGenCollectionStyle.Flat)
        {
            // Flat: the wrapper element is collapsed from the path perspective.
            // For optional collections (item-level), the wrapper may be absent
            // in some items — use FindElement + null guard instead of RequireElement.
            sb.AppendLine();
            string wrapperVarName = ToCamel(csharpPropertyName) + "WrapperEl";
            if (optional)
            {
                sb.Append(indent).Append("XmlSourceElement? ").Append(wrapperVarName)
                  .Append(" = ").Append(sourceElementVar)
                  .Append(".FindElement(\"").Append(EscapeForCsString(coll.WrapperElementName!))
                  .AppendLine("\");");
            }
            else
            {
                sb.Append(indent).Append("var ").Append(wrapperVarName)
                  .Append(" = ").Append(sourceElementVar)
                  .Append(".RequireElement(\"").Append(EscapeForCsString(coll.WrapperElementName!))
                  .AppendLine("\");");
            }
            EmitCollectionItemsInitFromWrapper(
                sb,
                coll: coll,
                csharpPropertyName: csharpPropertyName,
                wrapperVarName: wrapperVarName,
                parentPathPrefixExpr: parentPathPrefixExpr,
                contextExpr: contextExpr,
                indent: indent,
                optional: optional);
        }
        else
        {
            // SiblingGroup: iterate sourceElementVar's children directly.
            sb.AppendLine();
            EmitCollectionItemsInitFromWrapper(
                sb,
                coll: coll,
                csharpPropertyName: csharpPropertyName,
                wrapperVarName: sourceElementVar,
                parentPathPrefixExpr: parentPathPrefixExpr,
                contextExpr: contextExpr,
                indent: indent);
        }
    }

    private static void EmitCollectionItemsInit(
        StringBuilder sb,
        XmlGenCollection coll,
        string csharpPropertyName,
        string sourceElementVar,
        string parentPathPrefixExpr,
        string contextExpr,
        bool wrapperFlattenedSource,
        string indent)
    {
        // Used by the wrapper class itself to populate its inner collection.
        EmitCollectionItemsInitFromWrapper(
            sb,
            coll,
            csharpPropertyName,
            wrapperVarName: sourceElementVar,
            parentPathPrefixExpr: parentPathPrefixExpr,
            contextExpr: contextExpr,
            indent: indent);
    }

    /// <summary>
    /// Emits the loop body that walks the children of <paramref name="wrapperVarName"/>
    /// and builds the collection, storing into the backing field
    /// <c>_{camelCase(csharpPropertyName)}</c>.
    /// </summary>
    private static void EmitCollectionItemsInitFromWrapper(
        StringBuilder sb,
        XmlGenCollection coll,
        string csharpPropertyName,
        string wrapperVarName,
        string parentPathPrefixExpr,
        string contextExpr,
        string indent,
        bool optional = false)
    {
        string listVar = "list_" + ToCamel(csharpPropertyName);
        string indexVar = "idx_" + ToCamel(csharpPropertyName);
        string elVar = "el_" + ToCamel(csharpPropertyName);

        // For optional wrappers (present in some items but not all), the loop
        // is guarded by a null check so absent items get an empty collection.
        string loopIndent = optional ? indent + "    " : indent;

        if (coll.ItemIsPureTextLeaf)
        {
            sb.Append(indent).Append("var ").Append(listVar)
              .AppendLine(" = new System.Collections.Generic.List<string>();");
            if (optional)
            {
                sb.Append(indent).Append("if (").Append(wrapperVarName).AppendLine(" != null)");
                sb.Append(indent).AppendLine("{");
            }
            sb.Append(loopIndent).Append("foreach (XmlSourceNode node in ")
              .Append(wrapperVarName).AppendLine(".Children)");
            sb.Append(loopIndent).AppendLine("{");
            sb.Append(loopIndent).Append("    if (node is XmlSourceElement ").Append(elVar)
              .Append(" && string.Equals(").Append(elVar)
              .Append(".Name, \"").Append(EscapeForCsString(coll.ItemElementName))
              .AppendLine("\", System.StringComparison.Ordinal))");
            sb.Append(loopIndent).AppendLine("    {");
            sb.Append(loopIndent).Append("        ").Append(listVar)
              .Append(".Add(").Append(elVar).Append(".Children.Count > 0 && ")
              .Append(elVar).Append(".Children[0] is XmlSourceText t_").Append(ToCamel(csharpPropertyName))
              .Append(" ? t_").Append(ToCamel(csharpPropertyName))
              .AppendLine(".Value : string.Empty);");
            sb.Append(loopIndent).AppendLine("    }");
            sb.Append(loopIndent).AppendLine("}");
            if (optional)
            {
                sb.Append(indent).AppendLine("}");
            }
            sb.Append(indent).Append("_").Append(ToCamel(csharpPropertyName))
              .Append(" = ").Append(listVar).AppendLine(";");
        }
        else
        {
            sb.Append(indent).Append("var ").Append(listVar)
              .Append(" = new System.Collections.Generic.List<")
              .Append(coll.ItemTypeName).AppendLine(">();");
            sb.Append(indent).Append("int ").Append(indexVar).AppendLine(" = 0;");
            if (optional)
            {
                sb.Append(indent).Append("if (").Append(wrapperVarName).AppendLine(" != null)");
                sb.Append(indent).AppendLine("{");
            }
            sb.Append(loopIndent).Append("foreach (XmlSourceNode node in ")
              .Append(wrapperVarName).AppendLine(".Children)");
            sb.Append(loopIndent).AppendLine("{");
            sb.Append(loopIndent).Append("    if (node is XmlSourceElement ").Append(elVar)
              .Append(" && string.Equals(").Append(elVar)
              .Append(".Name, \"").Append(EscapeForCsString(coll.ItemElementName))
              .AppendLine("\", System.StringComparison.Ordinal))");
            sb.Append(loopIndent).AppendLine("    {");
            sb.Append(loopIndent).Append("        ").Append(listVar)
              .Append(".Add(new ").Append(coll.ItemTypeName).Append("(")
              .Append(contextExpr).Append(", ")
              .Append(parentPathPrefixExpr).Append(" + \"/").Append(csharpPropertyName)
              .Append("/\" + ").Append(indexVar).Append(", ")
              .Append(elVar).AppendLine("));");
            sb.Append(loopIndent).Append("        ").Append(indexVar).AppendLine("++;");
            sb.Append(loopIndent).AppendLine("    }");
            sb.Append(loopIndent).AppendLine("}");
            if (optional)
            {
                sb.Append(indent).AppendLine("}");
            }
            sb.Append(indent).Append("_").Append(ToCamel(csharpPropertyName))
              .Append(" = ").Append(listVar).AppendLine(";");
        }
    }

    private static void EmitCollectionProperty(
        StringBuilder sb,
        XmlGenCollection coll,
        string csharpPropertyName,
        string indent = "    ")
    {
        sb.AppendLine();
        if (coll.Style == XmlGenCollectionStyle.Wrapper)
        {
            string wrapperTypeName = WrapperTypeName(coll);
            sb.Append(indent).Append("public ").Append(wrapperTypeName).Append(" ")
              .Append(csharpPropertyName).Append(" => _")
              .Append(ToCamel(csharpPropertyName)).AppendLine(";");
        }
        else
        {
            sb.Append(indent).Append("public IReadOnlyList<").Append(coll.ItemTypeName).Append("> ")
              .Append(csharpPropertyName).Append(" => _")
              .Append(ToCamel(csharpPropertyName)).AppendLine(";");
        }
    }

    // ── Root scalar emission ─────────────────────────────────────────────────

    private static void EmitRootScalarCtor(StringBuilder sb, RootScalar s)
    {
        sb.Append("        var ").Append(s.LookupVarName)
          .Append(" = ").Append(s.LookupExpr).AppendLine(";");
        sb.Append("        _").Append(s.CamelName).Append("ValueSpan = ")
          .Append(s.LookupVarName).Append(s.SpanExpr).AppendLine(";");
        sb.Append("        _").Append(s.CamelName).Append(" = ").Append(s.CtorExpr).AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitRootScalarProperty(StringBuilder sb, RootScalar s)
    {
        sb.AppendLine();
        sb.Append("    public ").Append(s.CSharpType).Append(' ').AppendLine(s.PascalName);
        sb.AppendLine("    {");
        sb.Append("        get => _").Append(s.CamelName).AppendLine(";");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.Append("            _").Append(s.CamelName).AppendLine(" = value;");
        sb.Append("            _ctx.Record(\"").Append(s.Path).Append("\", _").Append(s.CamelName)
          .Append("ValueSpan, ").Append(s.WriterCall).AppendLine(");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // ── Item scalar emission (FindElement + IsPresent + throwing setter) ────

    private static void EmitItemScalarCtor(StringBuilder sb, ItemScalar s)
    {
        if (s.IsAttribute)
        {
            sb.AppendLine();
            sb.Append("            var ").Append(s.LookupVarName)
              .Append(" = element.FindAttribute(\"")
              .Append(EscapeForCsString(s.XmlName)).AppendLine("\");");
            sb.Append("            _").Append(s.CamelName).Append("IsPresent = ")
              .Append(s.LookupVarName).AppendLine(" is not null;");
            sb.Append("            _").Append(s.CamelName).Append("ValueSpan = ")
              .Append(s.LookupVarName).Append("?.ValueSpan ?? default;");
            sb.AppendLine();
            sb.Append("            _").Append(s.CamelName).Append(" = ")
              .Append(s.LookupVarName).Append(" is null ? ")
              .Append(DefaultValueExpr(s.Kind)).Append(" : ")
              .Append(s.AbsentSafeCtorExpr).AppendLine(";");
        }
        else
        {
            sb.AppendLine();
            sb.Append("            var ").Append(s.LookupVarName)
              .Append(" = element.FindElement(\"")
              .Append(EscapeForCsString(s.XmlName)).AppendLine("\");");
            sb.Append("            _").Append(s.CamelName).Append("IsPresent = ")
              .Append(s.LookupVarName).AppendLine(" is not null;");
            sb.Append("            _").Append(s.CamelName).Append("ValueSpan = ")
              .Append(s.LookupVarName).Append("?.InnerSpan ?? default;");
            sb.Append("            _").Append(s.CamelName).Append(" = ")
              .Append(s.LookupVarName).Append(" is null ? ")
              .Append(DefaultValueExpr(s.Kind)).Append(" : ")
              .Append(s.AbsentSafeCtorExpr).AppendLine(";");
        }
    }

    private static void EmitItemScalarProperty(StringBuilder sb, ItemScalar s, string itemXmlElementName)
    {
        sb.AppendLine();
        sb.Append("        public ").Append(s.CSharpType).Append(' ').AppendLine(s.PascalName);
        sb.AppendLine("        {");
        sb.Append("            get => _").Append(s.CamelName).AppendLine(";");
        sb.AppendLine("            set");
        sb.AppendLine("            {");
        sb.Append("                if (!_").Append(s.CamelName).AppendLine("IsPresent)");
        sb.AppendLine("                {");
        sb.Append("                    throw new StructuraMutationException(")
          .Append("\"Cannot update field '")
          .Append(EscapeForCsString(s.PascalName))
          .Append("' on this <")
          .Append(EscapeForCsString(itemXmlElementName))
          .Append("> because the source element is absent. ")
          .Append("Insertion is not supported in V1; this field exists in the model only because some other ")
          .Append("<").Append(EscapeForCsString(itemXmlElementName)).AppendLine("> sibling provided it.\");");
        sb.AppendLine("                }");
        sb.Append("                _").Append(s.CamelName).AppendLine(" = value;");
        sb.Append("                _ctx.Record(_pathPrefix + \"/").Append(s.PascalName)
          .Append("\", _").Append(s.CamelName).Append("ValueSpan, ")
          .Append(s.WriterCall).AppendLine(");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    // ── Nested-object scalar emission (RequireElement, no IsPresent guard) ──

    private static void EmitNestedScalarCtor(StringBuilder sb, NestedScalar s, string indent)
    {
        sb.AppendLine();
        if (s.IsAttribute)
        {
            sb.Append(indent).Append("var ").Append(s.LookupVarName)
              .Append(" = element.RequireAttribute(\"")
              .Append(EscapeForCsString(s.XmlName)).AppendLine("\");");
            sb.Append(indent).Append("_").Append(s.CamelName).Append("ValueSpan = ")
              .Append(s.LookupVarName).AppendLine(".ValueSpan;");
            sb.Append(indent).Append("_").Append(s.CamelName).Append(" = ")
              .Append(s.CtorExpr).AppendLine(";");
        }
        else
        {
            sb.Append(indent).Append("var ").Append(s.LookupVarName)
              .Append(" = element.RequireElement(\"")
              .Append(EscapeForCsString(s.XmlName)).AppendLine("\");");
            sb.Append(indent).Append("_").Append(s.CamelName).Append("ValueSpan = ")
              .Append(s.LookupVarName).AppendLine(".InnerSpan;");
            sb.Append(indent).Append("_").Append(s.CamelName).Append(" = ")
              .Append(s.CtorExpr).AppendLine(";");
        }
    }

    private static void EmitNestedScalarProperty(
        StringBuilder sb,
        NestedScalar s,
        string classIndent,
        string bodyIndent)
    {
        sb.AppendLine();
        sb.Append(classIndent).Append("public ").Append(s.CSharpType).Append(' ')
          .AppendLine(s.PascalName);
        sb.Append(classIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("get => _").Append(s.CamelName).AppendLine(";");
        sb.Append(bodyIndent).AppendLine("set");
        sb.Append(bodyIndent).AppendLine("{");

        string innerIndent = bodyIndent + "    ";
        sb.Append(innerIndent).Append("_").Append(s.CamelName).AppendLine(" = value;");
        sb.Append(innerIndent).Append("_ctx.Record(_pathPrefix + \"").Append(s.PathSuffix)
          .Append("\", _").Append(s.CamelName).Append("ValueSpan, ")
          .Append(s.WriterCall).AppendLine(");");

        sb.Append(bodyIndent).AppendLine("}");
        sb.Append(classIndent).AppendLine("}");
    }

    private static NestedScalar BuildNestedScalar(XmlGenProperty prop, HashSet<string> usedNames)
    {
        string pascalName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        string camelName = ToCamel(pascalName);

        if (prop.IsAttribute)
        {
            (string csharpType, string ctorExpr, string writerCall) = AttributeBindings(prop.Kind, camelName + "Attr");
            return new NestedScalar(
                xmlName: prop.Name,
                pascalName: pascalName,
                camelName: camelName,
                csharpType: csharpType,
                isAttribute: true,
                lookupVarName: camelName + "Attr",
                ctorExpr: ctorExpr,
                writerCall: writerCall,
                pathSuffix: "/@" + prop.Name);
        }

        // Match the safe-on-empty pattern from BuildItemScalar so empty
        // elements (<last-name></last-name>) read as empty strings rather
        // than crashing on Children[0].
        var textExpr = $"({camelName}El.Children.Count > 0 && {camelName}El.Children[0] is XmlSourceText t_{camelName} ? t_{camelName}.Value : string.Empty)";
        (string typeStr, string ctor, string writer) = ElementBindings(prop.Kind, textExpr);
        return new NestedScalar(
            xmlName: prop.Name,
            pascalName: pascalName,
            camelName: camelName,
            csharpType: typeStr,
            isAttribute: false,
            lookupVarName: camelName + "El",
            ctorExpr: ctor,
            writerCall: writer,
            pathSuffix: "/" + pascalName);
    }

    // ── Nested-object type emission (root and item-level call this) ──────────

    /// <summary>
    /// Emits the partial class for a nested-object body. Always sits at the
    /// top level of the outer document class (alongside item types and wrapper
    /// groups), so <paramref name="classIndent"/> is fixed at <c>"    "</c>;
    /// the parameter exists for symmetry with item emission and to keep the
    /// recursion uniform if we ever lower nested types in the future.
    /// </summary>
    private static void EmitNestedObjectType(StringBuilder sb, XmlGenNestedObject nested)
    {
        ItemTypeInfo body = nested.Body;
        string typeName = NestedObjectTypeName(nested.XmlElementName);

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var nestedScalars = new List<NestedScalar>();
        foreach (XmlGenProperty prop in body.Scalars)
        {
            nestedScalars.Add(BuildNestedScalar(prop, usedNames));
        }

        var collectionNames = new List<string>();
        foreach (XmlGenCollection coll in body.Collections)
        {
            string unique = MakeUnique(coll.CSharpPropertyName, usedNames);
            collectionNames.Add(unique);
        }

        var nestedBindings = new List<NestedObjectBinding>();
        foreach (XmlGenNestedObject inner in body.NestedObjects)
        {
            string propName = MakeUnique(IdentifierSanitizer.ToPascalCase(inner.XmlElementName), usedNames);
            nestedBindings.Add(new NestedObjectBinding(
                xmlElementName: inner.XmlElementName,
                propertyName: propName,
                fieldName: ToCamel(propName),
                typeName: NestedObjectTypeName(inner.XmlElementName)));
        }

        sb.AppendLine();
        sb.Append("    public sealed partial class ").AppendLine(typeName);
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly StructuraDocumentContext _ctx;");
        sb.AppendLine("        private readonly string _pathPrefix;");

        // Span + value fields for scalars.
        foreach (NestedScalar s in nestedScalars)
        {
            sb.AppendLine();
            sb.Append("        private readonly TextSpan _").Append(s.CamelName).AppendLine("ValueSpan;");
            sb.Append("        private ").Append(s.CSharpType).Append(" _").Append(s.CamelName).AppendLine(";");
        }

        // Backing fields for nested collections inside this nested object.
        for (var i = 0; i < body.Collections.Count; i++)
        {
            sb.AppendLine();
            EmitCollectionBackingField(sb, body.Collections[i], collectionNames[i], indent: "        ");
        }

        // Backing fields for further nested objects inside this nested object.
        foreach (NestedObjectBinding n in nestedBindings)
        {
            sb.AppendLine();
            sb.Append("        private readonly ").Append(n.TypeName).Append(" _")
              .Append(n.FieldName).AppendLine(";");
        }

        // Constructor.
        sb.AppendLine();
        sb.Append("        internal ").Append(typeName)
          .AppendLine("(StructuraDocumentContext ctx, string pathPrefix, XmlSourceElement element)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ctx = ctx;");
        sb.AppendLine("            _pathPrefix = pathPrefix;");

        foreach (NestedScalar s in nestedScalars)
        {
            EmitNestedScalarCtor(sb, s, indent: "            ");
        }

        for (var i = 0; i < body.Collections.Count; i++)
        {
            EmitCollectionCtor(
                sb,
                coll: body.Collections[i],
                csharpPropertyName: collectionNames[i],
                sourceElementVar: "element",
                parentPathPrefixExpr: "_pathPrefix",
                contextExpr: "_ctx",
                indent: "            ");
        }

        foreach (NestedObjectBinding n in nestedBindings)
        {
            sb.AppendLine();
            sb.Append("            var ").Append(n.FieldName).Append("El = element.RequireElement(\"")
              .Append(EscapeForCsString(n.XmlElementName)).AppendLine("\");");
            sb.Append("            _").Append(n.FieldName).Append(" = new ").Append(n.TypeName)
              .Append("(_ctx, _pathPrefix + \"/").Append(n.PropertyName).Append("\", ")
              .Append(n.FieldName).AppendLine("El);");
        }

        sb.AppendLine("        }");

        // Public properties.
        foreach (NestedScalar s in nestedScalars)
        {
            EmitNestedScalarProperty(sb, s, classIndent: "        ", bodyIndent: "            ");
        }

        for (var i = 0; i < body.Collections.Count; i++)
        {
            EmitCollectionProperty(sb, body.Collections[i], collectionNames[i], indent: "        ");
        }

        foreach (NestedObjectBinding n in nestedBindings)
        {
            sb.AppendLine();
            sb.Append("        public ").Append(n.TypeName).Append(' ').Append(n.PropertyName)
              .Append(" => _").Append(n.FieldName).AppendLine(";");
        }

        sb.AppendLine("    }");

        // Recurse: emit further nested-object types and collection nested types.
        foreach (XmlGenNestedObject inner in body.NestedObjects)
        {
            EmitNestedObjectType(sb, inner);
        }

        foreach (XmlGenCollection inner in body.Collections)
        {
            EmitNestedTypesForCollection(sb, inner);
        }
    }

    // ── Scalar info builders ─────────────────────────────────────────────────

    private static RootScalar BuildRootScalar(XmlGenProperty prop, HashSet<string> usedNames)
    {
        string pascalName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        string camelName = ToCamel(pascalName);

        if (prop.IsAttribute)
        {
            (string csharpType, string ctorExpr, string writerCall) = AttributeBindings(prop.Kind, camelName + "Attr");
            return new RootScalar(
                xmlName: prop.Name,
                pascalName: pascalName,
                camelName: camelName,
                csharpType: csharpType,
                lookupExpr: $"root.RequireAttribute(\"{EscapeForCsString(prop.Name)}\")",
                lookupVarName: camelName + "Attr",
                spanExpr: ".ValueSpan",
                ctorExpr: ctorExpr,
                writerCall: writerCall,
                path: "/@" + prop.Name);
        }

        (string typeStr, string ctor, string writer) = ElementBindings(prop.Kind, $"((XmlSourceText){camelName}El.Children[0]).Value");
        return new RootScalar(
            xmlName: prop.Name,
            pascalName: pascalName,
            camelName: camelName,
            csharpType: typeStr,
            lookupExpr: $"root.RequireElement(\"{EscapeForCsString(prop.Name)}\")",
            lookupVarName: camelName + "El",
            spanExpr: ".InnerSpan",
            ctorExpr: ctor,
            writerCall: writer,
            path: "/" + pascalName);
    }

    private static ItemScalar BuildItemScalar(XmlGenProperty prop, HashSet<string> usedNames)
    {
        string pascalName = IdentifierSanitizer.Sanitize(prop.Name, usedNames);
        string camelName = ToCamel(pascalName);

        if (prop.IsAttribute)
        {
            (string csharpType, string ctorExpr, string writerCall) = AttributeBindings(prop.Kind, camelName + "Attr");
            return new ItemScalar(
                xmlName: prop.Name,
                pascalName: pascalName,
                camelName: camelName,
                csharpType: csharpType,
                isAttribute: true,
                lookupVarName: camelName + "Attr",
                absentSafeCtorExpr: ctorExpr,
                writerCall: writerCall,
                kind: prop.Kind);
        }

        var textExpr = $"({camelName}El.Children.Count > 0 && {camelName}El.Children[0] is XmlSourceText t_{camelName} ? t_{camelName}.Value : string.Empty)";
        (string typeStr, string ctor, string writer) = ElementBindings(prop.Kind, textExpr);
        return new ItemScalar(
            xmlName: prop.Name,
            pascalName: pascalName,
            camelName: camelName,
            csharpType: typeStr,
            isAttribute: false,
            lookupVarName: camelName + "El",
            absentSafeCtorExpr: ctor,
            writerCall: writer,
            kind: prop.Kind);
    }

    private static (string csharpType, string ctorExpr, string writerCall) AttributeBindings(XmlGenScalarKind kind, string varName)
    {
        switch (kind)
        {
            case XmlGenScalarKind.String:
                return ("string",
                    $"{varName}.Value",
                    "XmlValueWriter.WriteAttributeValue(value)");
            case XmlGenScalarKind.Long:
                return ("long",
                    $"long.Parse({varName}.Value, CultureInfo.InvariantCulture)",
                    "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteInt64(value))");
            case XmlGenScalarKind.Decimal:
                return ("decimal",
                    $"decimal.Parse({varName}.Value, CultureInfo.InvariantCulture)",
                    "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteDecimal(value))");
            case XmlGenScalarKind.Boolean:
                return ("bool",
                    $"bool.Parse({varName}.Value)",
                    "XmlValueWriter.WriteAttributeValue(XmlValueWriter.WriteBoolean(value))");
            default:
                throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    private static (string csharpType, string ctorExpr, string writerCall) ElementBindings(XmlGenScalarKind kind, string textExpr)
    {
        switch (kind)
        {
            case XmlGenScalarKind.String:
                return ("string",
                    textExpr,
                    "XmlValueWriter.WriteElementText(value)");
            case XmlGenScalarKind.Long:
                return ("long",
                    $"long.Parse({textExpr}, CultureInfo.InvariantCulture)",
                    "XmlValueWriter.WriteInt64(value)");
            case XmlGenScalarKind.Decimal:
                return ("decimal",
                    $"decimal.Parse({textExpr}, CultureInfo.InvariantCulture)",
                    "XmlValueWriter.WriteDecimal(value)");
            case XmlGenScalarKind.Boolean:
                return ("bool",
                    $"bool.Parse({textExpr})",
                    "XmlValueWriter.WriteBoolean(value)");
            default:
                throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    private static string DefaultValueExpr(XmlGenScalarKind kind)
    {
        switch (kind)
        {
            case XmlGenScalarKind.String: return "string.Empty";
            case XmlGenScalarKind.Long: return "0L";
            case XmlGenScalarKind.Decimal: return "0m";
            case XmlGenScalarKind.Boolean: return "false";
            default: throw new InvalidOperationException("Unknown scalar kind.");
        }
    }

    // ── Misc helpers ─────────────────────────────────────────────────────────

    private static string MakeUnique(string baseName, HashSet<string> used)
    {
        if (used.Add(baseName))
        {
            return baseName;
        }
        var n = 2;
        while (true)
        {
            string candidate = baseName + n.ToString();
            if (used.Add(candidate))
            {
                return candidate;
            }
            n++;
        }
    }

    private static string ToCamel(string pascal)
    {
        if (string.IsNullOrEmpty(pascal))
        {
            return pascal;
        }
        var start = 0;
        while (start < pascal.Length && pascal[start] == '_')
        {
            start++;
        }
        if (start >= pascal.Length)
        {
            return pascal;
        }
        var sb = new StringBuilder(pascal.Length);
        sb.Append(pascal, 0, start);
        sb.Append(char.ToLowerInvariant(pascal[start]));
        if (pascal.Length > start + 1)
        {
            sb.Append(pascal, start + 1, pascal.Length - start - 1);
        }
        return sb.ToString();
    }

    private static string EscapeForCsString(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    // ── Internal scalar records ──────────────────────────────────────────────

    private sealed class RootScalar
    {
        public RootScalar(
            string xmlName,
            string pascalName,
            string camelName,
            string csharpType,
            string lookupExpr,
            string lookupVarName,
            string spanExpr,
            string ctorExpr,
            string writerCall,
            string path)
        {
            XmlName = xmlName;
            PascalName = pascalName;
            CamelName = camelName;
            CSharpType = csharpType;
            LookupExpr = lookupExpr;
            LookupVarName = lookupVarName;
            SpanExpr = spanExpr;
            CtorExpr = ctorExpr;
            WriterCall = writerCall;
            Path = path;
        }

        public string XmlName { get; }
        public string PascalName { get; }
        public string CamelName { get; }
        public string CSharpType { get; }
        public string LookupExpr { get; }
        public string LookupVarName { get; }
        public string SpanExpr { get; }
        public string CtorExpr { get; }
        public string WriterCall { get; }
        public string Path { get; }
    }

    private sealed class ItemScalar
    {
        public ItemScalar(
            string xmlName,
            string pascalName,
            string camelName,
            string csharpType,
            bool isAttribute,
            string lookupVarName,
            string absentSafeCtorExpr,
            string writerCall,
            XmlGenScalarKind kind)
        {
            XmlName = xmlName;
            PascalName = pascalName;
            CamelName = camelName;
            CSharpType = csharpType;
            IsAttribute = isAttribute;
            LookupVarName = lookupVarName;
            AbsentSafeCtorExpr = absentSafeCtorExpr;
            WriterCall = writerCall;
            Kind = kind;
        }

        public string XmlName { get; }
        public string PascalName { get; }
        public string CamelName { get; }
        public string CSharpType { get; }
        public bool IsAttribute { get; }
        public string LookupVarName { get; }
        public string AbsentSafeCtorExpr { get; }
        public string WriterCall { get; }
        public XmlGenScalarKind Kind { get; }
    }

    /// <summary>
    /// Scalar inside a nested-object body. Distinct from <see cref="ItemScalar"/>
    /// because nested-object scalars are required (single observation, no
    /// heterogeneous merging), so they use <c>RequireElement</c> /
    /// <c>RequireAttribute</c> directly and skip both the IsPresent flag and
    /// the throwing setter.
    /// </summary>
    private sealed class NestedScalar
    {
        public NestedScalar(
            string xmlName,
            string pascalName,
            string camelName,
            string csharpType,
            bool isAttribute,
            string lookupVarName,
            string ctorExpr,
            string writerCall,
            string pathSuffix)
        {
            XmlName = xmlName;
            PascalName = pascalName;
            CamelName = camelName;
            CSharpType = csharpType;
            IsAttribute = isAttribute;
            LookupVarName = lookupVarName;
            CtorExpr = ctorExpr;
            WriterCall = writerCall;
            PathSuffix = pathSuffix;
        }

        public string XmlName { get; }
        public string PascalName { get; }
        public string CamelName { get; }
        public string CSharpType { get; }
        public bool IsAttribute { get; }
        public string LookupVarName { get; }
        public string CtorExpr { get; }
        public string WriterCall { get; }
        public string PathSuffix { get; } // includes leading '/'
    }

    private sealed class NestedObjectBinding
    {
        public NestedObjectBinding(
            string xmlElementName,
            string propertyName,
            string fieldName,
            string typeName)
        {
            XmlElementName = xmlElementName;
            PropertyName = propertyName;
            FieldName = fieldName;
            TypeName = typeName;
        }

        public string XmlElementName { get; }
        public string PropertyName { get; }
        public string FieldName { get; }
        public string TypeName { get; }
    }
}
